/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ToastImport } from './routes/toast'
import { Route as TagImport } from './routes/tag'
import { Route as TabImport } from './routes/tab'
import { Route as SetupImport } from './routes/setup'
import { Route as SelectImport } from './routes/select'
import { Route as MenuImport } from './routes/menu'
import { Route as InputImport } from './routes/input'
import { Route as DialogImport } from './routes/dialog'
import { Route as CardImport } from './routes/card'
import { Route as ButtonImport } from './routes/button'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ToastRoute = ToastImport.update({
  path: '/toast',
  getParentRoute: () => rootRoute,
} as any)

const TagRoute = TagImport.update({
  path: '/tag',
  getParentRoute: () => rootRoute,
} as any)

const TabRoute = TabImport.update({
  path: '/tab',
  getParentRoute: () => rootRoute,
} as any)

const SetupRoute = SetupImport.update({
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any)

const SelectRoute = SelectImport.update({
  path: '/select',
  getParentRoute: () => rootRoute,
} as any)

const MenuRoute = MenuImport.update({
  path: '/menu',
  getParentRoute: () => rootRoute,
} as any)

const InputRoute = InputImport.update({
  path: '/input',
  getParentRoute: () => rootRoute,
} as any)

const DialogRoute = DialogImport.update({
  path: '/dialog',
  getParentRoute: () => rootRoute,
} as any)

const CardRoute = CardImport.update({
  path: '/card',
  getParentRoute: () => rootRoute,
} as any)

const ButtonRoute = ButtonImport.update({
  path: '/button',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonImport
      parentRoute: typeof rootRoute
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardImport
      parentRoute: typeof rootRoute
    }
    '/dialog': {
      id: '/dialog'
      path: '/dialog'
      fullPath: '/dialog'
      preLoaderRoute: typeof DialogImport
      parentRoute: typeof rootRoute
    }
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputImport
      parentRoute: typeof rootRoute
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuImport
      parentRoute: typeof rootRoute
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupImport
      parentRoute: typeof rootRoute
    }
    '/tab': {
      id: '/tab'
      path: '/tab'
      fullPath: '/tab'
      preLoaderRoute: typeof TabImport
      parentRoute: typeof rootRoute
    }
    '/tag': {
      id: '/tag'
      path: '/tag'
      fullPath: '/tag'
      preLoaderRoute: typeof TagImport
      parentRoute: typeof rootRoute
    }
    '/toast': {
      id: '/toast'
      path: '/toast'
      fullPath: '/toast'
      preLoaderRoute: typeof ToastImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ButtonRoute,
  CardRoute,
  DialogRoute,
  InputRoute,
  MenuRoute,
  SelectRoute,
  SetupRoute,
  TabRoute,
  TagRoute,
  ToastRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/button",
        "/card",
        "/dialog",
        "/input",
        "/menu",
        "/select",
        "/setup",
        "/tab",
        "/tag",
        "/toast"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/button": {
      "filePath": "button.tsx"
    },
    "/card": {
      "filePath": "card.tsx"
    },
    "/dialog": {
      "filePath": "dialog.tsx"
    },
    "/input": {
      "filePath": "input.tsx"
    },
    "/menu": {
      "filePath": "menu.tsx"
    },
    "/select": {
      "filePath": "select.tsx"
    },
    "/setup": {
      "filePath": "setup.tsx"
    },
    "/tab": {
      "filePath": "tab.tsx"
    },
    "/tag": {
      "filePath": "tag.tsx"
    },
    "/toast": {
      "filePath": "toast.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
